/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author José Alvarado
 */
public class Convertidor extends javax.swing.JFrame {
    public static int nFotosCargadas = 0;
    public static String texto = "Prcocesos realizados:";
    ColaImagen colaImagenes = new ColaImagen();

    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
        File directorio = new File("C:/Users/josed/Downloads/Temporal");
        if (!directorio.exists()) {
            directorio.mkdir();
        }
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                funcionEliminarCarpeta1(new File("C:/Users/josed/Downloads/Temporal")); 
            }
        });        
        
        texto = "Prcocesos realizados:";
        nFotosCargadas = 0;
        
        JComboBox modeloUsuarios = new JComboBox();
        for (int i = 0; i < AppState.usuarios.getSize(); i++) {
            modeloUsuarios.addItem(((Usuario) AppState.usuarios.get(i)).nombre);
        }
        Usuarios.setModel(modeloUsuarios.getModel());
        Usuarios.addItemListener(null);

        JComboBox modeloCategorias = new JComboBox();
        if (AppState.usuarios.getSize() > 0) {
            Usuario usuario1 = (Usuario) AppState.usuarios.get(0);
            for (int i = 0; i < usuario1.categorias.getSize(); i++) {
                modeloCategorias.addItem(((Categoria) usuario1.categorias.get(i)).nombre);
            }
        }
        Categoria.setModel(modeloCategorias.getModel());

        Usuarios.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent arg0) {
                if (arg0.getStateChange() == ItemEvent.SELECTED) {
                    String userName = Usuarios.getSelectedItem().toString();
                    JComboBox modeloCategorias = new JComboBox();
                    Usuario usuario1 = (Usuario) AppState.usuarios.find(userName);
                    for (int i = 0; i < usuario1.categorias.getSize(); i++) {
                        modeloCategorias.addItem(((Categoria) usuario1.categorias.get(i)).nombre);
                    }
                    Categoria.setModel(modeloCategorias.getModel());
                }
            }
        });
    }
    
    private static void funcionEliminarCarpeta1(File pArchivo) {
        if (!pArchivo.exists()) { return; }
        if (pArchivo.isDirectory()) {
            for (File f : pArchivo.listFiles()) {
                funcionEliminarCarpeta1(f);  }
        }
        pArchivo.delete();
    }         
    
    public static void cargar() {
        CantProcesada.setValue(nFotosCargadas);
        ConsolaDeEjecucion.setText(texto);
    }
    
    public void setMax() {
        int max = 0;
        max = JPEGaBMPyViceversa.isSelected()? max + 1 : max;
        max = CopiaJPEG.isSelected()? max + 1 : max;
        max = RojoVerdeAzulSepia.isSelected()? max + 1 : max;
        max = ModificarImagen.isSelected()? max + 1 : max;
        max = BlancoyNegro.isSelected()? max + 1 : max;
        max *= colaImagenes.getSize();
        CantProcesada.setMaximum(max);
    }

    public void render() {
        DefaultListModel modelo = new DefaultListModel();
        ColaImagen respaldo = new ColaImagen();
        Imagen imagen;
        int repeticion = colaImagenes.getSize();
        for (int i = 0; i < repeticion; i++) {
            imagen = (Imagen) colaImagenes.pop();
            modelo.addElement(imagen.nombre);
            respaldo.add(imagen);
        }
        ColaProcesamiento.setModel(modelo);
        colaImagenes = respaldo;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        Usuarios = new javax.swing.JComboBox();
        Categoria = new javax.swing.JComboBox();
        Agregar = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ColaProcesamiento = new javax.swing.JList();
        RojoVerdeAzulSepia = new javax.swing.JCheckBox();
        CopiaJPEG = new javax.swing.JCheckBox();
        JPEGaBMPyViceversa = new javax.swing.JCheckBox();
        ModificarImagen = new javax.swing.JCheckBox();
        BlancoyNegro = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        EjecutarEnParalelo = new javax.swing.JToggleButton();
        EjecutarEnFifo = new javax.swing.JToggleButton();
        EjecutarEnLifo = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        CantProcesada = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsolaDeEjecucion = new javax.swing.JTextArea();
        Volver = new javax.swing.JToggleButton();

        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        Agregar.setText("Agregar");
        Agregar.setFocusPainted(false);
        Agregar.setOpaque(true);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cola de Procesameinto");

        ColaProcesamiento.setFocusable(false);
        ColaProcesamiento.setRequestFocusEnabled(false);
        ColaProcesamiento.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ColaProcesamiento.setSelectionForeground(new java.awt.Color(0, 0, 0));
        ColaProcesamiento.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(ColaProcesamiento);

        RojoVerdeAzulSepia.setText("Rojo Verde Azul Sepia");

        CopiaJPEG.setText("copia JPEG");

        JPEGaBMPyViceversa.setText("JPEG a BMP y viceversa");

        ModificarImagen.setText("Modificar Imagen");

        BlancoyNegro.setText("Blanco y  Negro");

        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        EjecutarEnParalelo.setText("Ejecutar en paralelo");
        EjecutarEnParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarEnParaleloActionPerformed(evt);
            }
        });

        EjecutarEnFifo.setText("Ejecutar en Secuencia FIFO");
        EjecutarEnFifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarEnFifoActionPerformed(evt);
            }
        });

        EjecutarEnLifo.setText("Ejecutar en secuencia LIFO");
        EjecutarEnLifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarEnLifoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad Procesada");

        jLabel5.setText("Consola de ejcución");

        jLabel6.setText("Categoria");

        ConsolaDeEjecucion.setColumns(20);
        ConsolaDeEjecucion.setRows(5);
        jScrollPane2.setViewportView(ConsolaDeEjecucion);

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(479, 479, 479))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(RojoVerdeAzulSepia)
                                                            .addComponent(CopiaJPEG)
                                                            .addComponent(ModificarImagen)
                                                            .addComponent(BlancoyNegro)
                                                            .addComponent(JPEGaBMPyViceversa))
                                                        .addGap(50, 50, 50)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(67, 67, 67)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(EjecutarEnFifo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(EjecutarEnParalelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(EjecutarEnLifo)))
                                                    .addComponent(CantProcesada, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(232, 232, 232)
                                        .addComponent(jLabel4)))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(239, 239, 239))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Agregar)
                        .addComponent(Volver)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EjecutarEnParalelo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EjecutarEnLifo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EjecutarEnFifo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JPEGaBMPyViceversa)
                                        .addGap(2, 2, 2)
                                        .addComponent(CopiaJPEG)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RojoVerdeAzulSepia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ModificarImagen)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BlancoyNegro)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)))
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantProcesada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        Principal ventana = new Principal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        if (colaImagenes.getSize() == 0) {
            CantProcesada.setValue(0);
            ConsolaDeEjecucion.setText("");
        }
        texto = "Prcocesos realizados:";
        nFotosCargadas = 0;
        
        String userName = Usuarios.getSelectedItem().toString();
        Usuario usuario = (Usuario) AppState.usuarios.find(userName);
        String categoryName = Categoria.getSelectedItem().toString();
        Categoria categoria = (Categoria) usuario.categorias.find(categoryName);

        for (int i = 0; i < categoria.imagenes.getSize(); i++) {
            colaImagenes.add((Imagen) categoria.imagenes.getImagen(i));
        }
        render();
    }//GEN-LAST:event_AgregarActionPerformed

    public void runOptions(String path, boolean opcion1, boolean opcion2, boolean opcion3, boolean opcion4, boolean opcion5) {
        Thread jpgToBMP = new Thread(new RunHandlerThread(new JPEGtoBMPImage(path)));
        Thread bmpToJPEG = new Thread(new RunHandlerThread(new BMPtoJPEGImage(path)));
        Thread copiaJPEG = new Thread(new RunHandlerThread(new JPEGImageCopy(path)));
        Thread jpegcolors = new Thread(new RunHandlerThread(new JPEGImageHandlerColors(path)));
        Thread transform = new Thread(new RunHandlerThread(new JPEGImageHandlerRotator(path)));
        Thread blancoNegro = new Thread(new RunHandlerThread(new JPEGImageHandlerBN(path)));
        String extension = "";
        int pos = path.lastIndexOf('.');
        extension = path.toString().substring(pos + 1);         
        boolean isJPEG = "jpg".equals(extension);
        
        if (opcion1) {
            if (isJPEG) {              
                jpgToBMP.start();
            } else {
                bmpToJPEG.start();
            }
        }
        if (opcion2) {
            copiaJPEG.start();
        }
        if (opcion3) {
            jpegcolors.start();
        }
        if (opcion4) {
            transform.start();
        }
        if (opcion5) {
            blancoNegro.start();
        }
    }

    private void EjecutarEnParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarEnParaleloActionPerformed
        setMax();
        boolean opcion1 = JPEGaBMPyViceversa.isSelected();
        boolean opcion2 = CopiaJPEG.isSelected();
        boolean opcion3 = RojoVerdeAzulSepia.isSelected();
        boolean opcion4 = ModificarImagen.isSelected();
        boolean opcion5 = BlancoyNegro.isSelected();
        int nRepeticion = colaImagenes.index;
        for (int i = 0; i < nRepeticion; i++) {
            Imagen imagen = (Imagen) colaImagenes.pop();
            runOptions(imagen.path.toString(), opcion1, opcion2, opcion3, opcion4, opcion5);
        } 
        render();
    }//GEN-LAST:event_EjecutarEnParaleloActionPerformed

    private void EjecutarEnLifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarEnLifoActionPerformed
        setMax();
        int nRepeticion = colaImagenes.index;
        Imagen[] lista = new Imagen[nRepeticion];
        for (int i = 0; i < nRepeticion; i++) {
            lista[nRepeticion - i - 1] = (Imagen) colaImagenes.pop();
        }
        for (int i = 0; i < nRepeticion; i++) {
            Imagen imagen = lista[i];
            if (JPEGaBMPyViceversa.isSelected()) {
                int pos = imagen.path.toString().lastIndexOf('.');
                String extension =  imagen.path.toString().substring(pos + 1); 
                if ("jpg".equals(extension)) {              
                   try { JPEGHandler.runHandler(new JPEGtoBMPImage(imagen.path.toString())); } catch(Exception e){};
                } else {
                    try { JPEGHandler.runHandler(new BMPtoJPEGImage(imagen.path.toString())); } catch(Exception e){};
                }
            }
            if (CopiaJPEG.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageCopy(imagen.path.toString())); } catch(Exception e){};
            }
            if (RojoVerdeAzulSepia.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageHandlerColors(imagen.path.toString())); } catch(Exception e){};
            }
            if (ModificarImagen.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageHandlerRotator(imagen.path.toString())); } catch(Exception e){};
            }
            if (BlancoyNegro.isSelected()) {
                 try { JPEGHandler.runHandler(new JPEGImageHandlerBN(imagen.path.toString())); } catch(Exception e){};
            }
        }
        render();
    }//GEN-LAST:event_EjecutarEnLifoActionPerformed

    private void EjecutarEnFifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarEnFifoActionPerformed
        setMax();
        int nRepeticion = colaImagenes.index;
        for (int i = 0; i < nRepeticion; i++) {
            Imagen imagen = (Imagen) colaImagenes.pop();
            if (JPEGaBMPyViceversa.isSelected()) {
                int pos = imagen.path.toString().lastIndexOf('.');
                String extension =  imagen.path.toString().substring(pos + 1); 
                if ("jpg".equals(extension)) {              
                   try { JPEGHandler.runHandler(new JPEGtoBMPImage(imagen.path.toString())); } catch(Exception e){};
                } else {
                    try { JPEGHandler.runHandler(new BMPtoJPEGImage(imagen.path.toString())); } catch(Exception e){};
                }
            }
            if (CopiaJPEG.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageCopy(imagen.path.toString())); } catch(Exception e){};
            }
            if (RojoVerdeAzulSepia.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageHandlerColors(imagen.path.toString())); } catch(Exception e){};
            }
            if (ModificarImagen.isSelected()) {
                try { JPEGHandler.runHandler(new JPEGImageHandlerRotator(imagen.path.toString())); } catch(Exception e){};
            }
            if (BlancoyNegro.isSelected()) {
                 try { JPEGHandler.runHandler(new JPEGImageHandlerBN(imagen.path.toString())); } catch(Exception e){};
            }
        } 
        render();
    }//GEN-LAST:event_EjecutarEnFifoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    private class ItemChangeListener implements ItemListener {

        @Override
        public void itemStateChanged(ItemEvent event) {
            if (event.getSource() == Usuarios) {
                String userName = Usuarios.getSelectedItem().toString();
                JComboBox modeloCategorias = new JComboBox();
                Usuario usuario1 = (Usuario) AppState.usuarios.find(userName);
                for (int i = 0; i < usuario1.categorias.getSize(); i++) {
                    modeloCategorias.addItem(((Categoria) usuario1.categorias.get(i)).nombre);
                }
                Categoria.setModel(modeloCategorias.getModel());
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Agregar;
    private javax.swing.JCheckBox BlancoyNegro;
    public static javax.swing.JProgressBar CantProcesada;
    private javax.swing.JComboBox Categoria;
    private javax.swing.JList ColaProcesamiento;
    public static javax.swing.JTextArea ConsolaDeEjecucion;
    private javax.swing.JCheckBox CopiaJPEG;
    private javax.swing.JToggleButton EjecutarEnFifo;
    private javax.swing.JToggleButton EjecutarEnLifo;
    private javax.swing.JToggleButton EjecutarEnParalelo;
    private javax.swing.JCheckBox JPEGaBMPyViceversa;
    private javax.swing.JCheckBox ModificarImagen;
    private javax.swing.JCheckBox RojoVerdeAzulSepia;
    private javax.swing.JComboBox Usuarios;
    private javax.swing.JToggleButton Volver;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
